// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaquinhaWebAPI.Data;

#nullable disable

namespace VaquinhaWebAPI.Migrations
{
    [DbContext(typeof(VaquinhaContext))]
    [Migration("20230529120151_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VaquinhaWebAPI.Models.CategoriaItemDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CATEGORIA_ITEM_DESPESA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeCategoriaItemDespesa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NM_CATEGORIA_ITEM_DESPESA");

                    b.HasKey("Id");

                    b.ToTable("CATEGORIA_ITEM_DESPESA");
                });

            modelBuilder.Entity("VaquinhaWebAPI.Models.ItemDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ITEM_DESPESA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaItemDespesaId")
                        .HasColumnType("int")
                        .HasColumnName("ID_CATEGORIA_ITEM_DESPESA");

                    b.Property<string>("DescricaoItemDespesa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DS_ITEM_DESPESA");

                    b.Property<DateTime>("DtItemDespesa")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_ITEM_DESPESA");

                    b.Property<int>("TipoItemDespesaId")
                        .HasColumnType("int")
                        .HasColumnName("ID_TIPO_ITEM_DESPESA");

                    b.Property<double>("ValorItemDespesa")
                        .HasColumnType("float")
                        .HasColumnName("NR_VALOR");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaItemDespesaId");

                    b.HasIndex("TipoItemDespesaId");

                    b.ToTable("ITEM_DESPESA");
                });

            modelBuilder.Entity("VaquinhaWebAPI.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PAGAMENTO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemDespesaId")
                        .HasColumnType("int")
                        .HasColumnName("ID_ITEM_DESPESA");

                    b.Property<int>("PaganteId")
                        .HasColumnType("int")
                        .HasColumnName("ID_PAGANTE");

                    b.Property<int>("PercentualPago")
                        .HasColumnType("int")
                        .HasColumnName("NR_PERCENTUAL_PAGO");

                    b.HasKey("Id");

                    b.HasIndex("ItemDespesaId");

                    b.HasIndex("PaganteId");

                    b.ToTable("PAGAMENTO");
                });

            modelBuilder.Entity("VaquinhaWebAPI.Models.Pagante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PAGANTE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomePagante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NM_NOME");

                    b.Property<string>("SobrenomePagante")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NM_SOBRENOME");

                    b.HasKey("Id");

                    b.ToTable("PAGANTE");
                });

            modelBuilder.Entity("VaquinhaWebAPI.Models.TipoItemDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TIPO_ITEM_DESPESA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeTipoItemDespesa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NM_TIPO_ITEM_DESPESA");

                    b.HasKey("Id");

                    b.ToTable("TIPO_ITEM_DESPESA");
                });

            modelBuilder.Entity("VaquinhaWebAPI.Models.ItemDespesa", b =>
                {
                    b.HasOne("VaquinhaWebAPI.Models.CategoriaItemDespesa", "CategoriaItemDespesa")
                        .WithMany()
                        .HasForeignKey("CategoriaItemDespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaquinhaWebAPI.Models.TipoItemDespesa", "TipoItemDespesa")
                        .WithMany()
                        .HasForeignKey("TipoItemDespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaItemDespesa");

                    b.Navigation("TipoItemDespesa");
                });

            modelBuilder.Entity("VaquinhaWebAPI.Models.Pagamento", b =>
                {
                    b.HasOne("VaquinhaWebAPI.Models.ItemDespesa", "ItemDespesa")
                        .WithMany()
                        .HasForeignKey("ItemDespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaquinhaWebAPI.Models.Pagante", "Pagante")
                        .WithMany()
                        .HasForeignKey("PaganteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDespesa");

                    b.Navigation("Pagante");
                });
#pragma warning restore 612, 618
        }
    }
}
